name: astrology_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  intl_phone_field: ^3.0.1
  pinput: ^2.2.31
  intl: ^0.17.0
  
  #google location dependency....
  flutter_google_places: ^0.3.0
  location: ^4.3.0
  google_maps_flutter: ^2.2.5
  geocode: ^1.0.2
  geocoding: ^2.0.5

  # Radio Button
  custom_radio_grouped_button: any
  flutter_radio_group: ^2.1.0

  flutter_switch: ^0.3.2


  

  floating_bottom_navigation_bar: ^1.5.2
  smooth_star_rating_nsafe: 1.0.0+1
  camera: ^0.10.5+2
  flutter_fortune_wheel: ^1.3.0
  razorpay_flutter: ^1.3.3
  socket_io_client: ^2.0.3+1
  flip_card: ^0.7.0
  scroll_snap_list: ^0.9.1
  dotted_border: ^2.0.0+3
  lottie: ^2.6.0
  kbspinningwheel: ^1.0.3
  package_info_plus: ^4.1.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.2
  image_picker: ^1.0.2
  image_cropper: ^4.0.1
  cached_network_image: ^3.2.3
  video_player: ^2.7.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  percent_indicator: ^4.2.3
  path: ^1.8.3
  
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/categoryIcons/
    - assets/images/astrologers/
    - assets/images/sunsigns/
    - assets/images/splash/
    - assets/riveAssets/
    - assets/lottie/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
