import 'package:flutter/material.dart';

import '../profile/user_all_calss.dart';

class KPKundliPage extends StatefulWidget {
  const KPKundliPage({super.key});

  @override
  State<KPKundliPage> createState() => _KPKundliPageState();
}

class _KPKundliPageState extends State<KPKundliPage> {
  @override
  Widget build(BuildContext context) {
    //var height = MediaQuery.of(context).size.height;
    var width = MediaQuery.of(context).size.width;
    return SingleChildScrollView(
      child: Padding(
        padding: EdgeInsets.only(bottom: width * .024),
        child: Column(
          children: [
            const KPage(text: 'Ashtakvarga Chart '),
            SizedBox(
              height: width * .035,
            ),
            Image.asset(
              'assets/images/charts.png',
              width: width * 0.99,
            ),
            SizedBox(
              height: width * .025,
            ),
            const KPage(text: 'Ruling Planets'),
            SizedBox(
              height: width * .025,
            ),
            ClipRRect(
              borderRadius: BorderRadius.circular(15),
              child: DataTable(
                columnSpacing: width * 0.07,
                border: TableBorder.all(
                    width: 1,
                    color: Colors.white,
                    style: BorderStyle.solid,
                    borderRadius: BorderRadius.circular(15)),
                headingRowColor: MaterialStateProperty.all(Colors.blue),
                headingTextStyle: TextStyle(
                  color: Colors.white,
                  fontSize: width * 0.03,
                ),
                columns: const [
                  DataColumn(label: Text('--', textAlign: TextAlign.center)),
                  DataColumn(
                    label: Text('Sign Lord', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Star Lord', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Sub Lord', textAlign: TextAlign.center),
                  ),
                ],
                rows: [
                  DataRow(cells: [
                    DataCell(Text(
                      'Mo',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.white, fontSize: width * 0.026),
                    )),
                    DataCell(Text('Venus',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Rahu',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mars',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    // DataCell(Text('1',textAlign: TextAlign.center,style: TextStyle(color: Colors.white,fontSize: 10))),
                    //DataCell(Text('6')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('Asc',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mercury',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Rahu',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Rahu',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                  ]),
                  // DataRow(cells: [
                  //   DataCell(Text('',
                  //       textAlign: TextAlign.center,
                  //       style: TextStyle(color: Colors.white, fontSize: 10))),
                  //   DataCell(Text('',
                  //       textAlign: TextAlign.center,
                  //       style: TextStyle(color: Colors.white, fontSize: 10))),
                  //   DataCell(Text('',
                  //       textAlign: TextAlign.center,
                  //       style: TextStyle(color: Colors.white, fontSize: 10))),
                  //   DataCell(Text('',
                  //       textAlign: TextAlign.center,
                  //       style: TextStyle(color: Colors.white, fontSize: 10))),
                  // ]),
                ],
              ),
            ),
            SizedBox(
              height: width * .025,
            ),
            const KPage(text: 'Planets'),
            SizedBox(
              height: width * .025,
            ),
            ClipRRect(
              borderRadius: BorderRadius.circular(15),
              child: DataTable(
                columnSpacing: width * .03,
                border: TableBorder.all(
                    width: 1,
                    color: Colors.white,
                    style: BorderStyle.solid,
                    borderRadius: BorderRadius.circular(15)),
                headingRowColor: MaterialStateProperty.all(Colors.blue),
                headingTextStyle: TextStyle(
                  color: const Color.fromRGBO(255, 255, 255, 1),
                  fontSize: width * 0.029,
                ),
                columns: const [
                  DataColumn(label: Text('Planet', textAlign: TextAlign.center)),
                  DataColumn(
                    label: Text('Cusp', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Sign', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Sign Lord', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Star lord', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Sub Lord', textAlign: TextAlign.center),
                  ),
                ],
                rows: [
                  DataRow(cells: [
                    DataCell(Text(
                      'Sun',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.white, fontSize: width * 0.026),
                    )),
                    DataCell(Text('9',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Capricorn',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Su',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ve',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('6')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('Moon',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('12',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Taurus',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ve',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mo',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Me',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('9')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('Mars',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('8',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Capricorn',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Su',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ju',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('Rahu',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('6',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Scorpio',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ma',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Me',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('Jupiter',
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('6',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Libra',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ve',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ra',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mo',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('Saturn',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('9',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Aquarius',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ma',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mo',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                ],
              ),
            ),
            SizedBox(
              height: width * 0.026,
            ),
            const KPage(text: 'Cusp'),
            SizedBox(
              height: width * 0.026,
            ),
            ClipRRect(
              borderRadius: BorderRadius.circular(15),
              child: DataTable(
                columnSpacing: width * 0.03,
                border: TableBorder.all(
                    width: 1,
                    color: Colors.white,
                    style: BorderStyle.solid,
                    borderRadius: BorderRadius.circular(15)),
                headingRowColor: MaterialStateProperty.all(Colors.blue),
                headingTextStyle: TextStyle(
                  color: Colors.white,
                  fontSize: width * 0.029,
                ),
                columns: const [
                  DataColumn(label: Text('Cusp', textAlign: TextAlign.center)),
                  DataColumn(
                    label: Text('Degree', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Sign', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Sign Lord', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Star lord', textAlign: TextAlign.center),
                  ),
                  DataColumn(
                    label: Text('Star lord', textAlign: TextAlign.center),
                  ),
                ],
                rows: [
                  DataRow(cells: [
                    DataCell(Text(
                      '1',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.white, fontSize: width * 0.026),
                    )),
                    DataCell(Text('9',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Capricorn',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Su',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ve',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('6')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('2',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('12',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Taurus',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ve',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mo',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Me',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('9')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('3',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('8',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Capricorn',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Su',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ju',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('4',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('6',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Scorpio',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ma',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Me',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('5',
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('6',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Libra',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ve',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ra',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mo',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                  DataRow(cells: [
                    DataCell(Text('6',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('9',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Aquarius',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Sa',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Ma',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    DataCell(Text('Mo',
                        textAlign: TextAlign.center,
                        style: TextStyle(color: Colors.white, fontSize: width * 0.026))),
                    //DataCell(Text('8')),
                  ]),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
